name: Test and Build

on:
  pull_request: {}
  push:
    branches:
      - master

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  UNITY_VERSION: 2020.2.2f1
  PROJECT_NAME: "GGJ Game"

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.build.outputs.buildVersion }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          lfs: true

      - uses: actions/cache@v2
        with:
          path: src/Library
          key: Library

      # - name: Run tests
      #   uses: game-ci/unity-test-runner@v2.0-alpha-2
      #   with:
      #     projectPath: src
      #     unityVersion: ${{ env.UNITY_VERSION }}

      - name: Build project
        id: build
        uses: game-ci/unity-builder@v2.0-alpha-6
        with:
          projectPath: src
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: StandaloneWindows

      - uses: actions/upload-artifact@v1
        with:
          name: Build
          path: build

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Clone Wiki
      uses: actions/checkout@v2
      with:
        repository: ${{github.repository}}.wiki
        path: press

    - name: Download build artifacts
      uses: actions/download-artifact@v2
      with:
        name: Build
        path: release

    - name: Zip it
      run: |
        # mv build release
        zip $PROJECT_NAME.zip -r . -x '*.git*'

    - name: Create release with binaries
      run: |
        gh release create v$GIT_TAG -t "Release v$GIT_TAG" $PROJECT_NAME.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GIT_TAG: ${{ needs.build.outputs.version }}
